GET http://localhost:3000/api/estado-cuenta/info-cliente
  ?rfc=FOBD891211MX4

###
GET http://localhost:3000/api/estado-cuenta/estados
  ?rfc=GOUJ5507242K5

###
POST http://localhost:3000/api/estado-cuenta/enviar-codigo
  Content-Type: application/json

{
  "celular": "2281237048",
  "rfc": "TOMB971024UW4"
}

###
POST http://localhost:3000/api/estado-cuenta/validar-codigo
  Content-Type: application/json

{
  "rfc": "TOMB971024UW4",
  "codigo": "869284"
}