GET http://localhost:3000/api/estado-cuenta/info-cliente
  ?rfc=TEST651002AJ1

###
GET http://localhost:3000/api/estado-cuenta/estados
  ?rfc=GODR830305J19

###
POST http://localhost:3000/api/estado-cuenta/enviar-codigo
  Content-Type: application/json

{
  "celular": "2281237048",
  "rfc": "TOMB971024UW4"
}

###
POST http://localhost:3000/api/estado-cuenta/validar-codigo
  Content-Type: application/json

{
  "rfc": "TOMB971024UW4",
  "codigo": "869284"
}

###

POST http://localhost:3000/api/estado-cuenta/imprimir
  Content-Type: application/json

{
  "rfc": "TOMB971024UW4",
  "codigo": "869284"
}

###
POST http://localhost:3000/api/estado-cuenta/generar-pdf
  Content-Type: application/json

{
  "idOrden": 714442
}