GET http://localhost:3000/api/cliente/buscar-cliente
  ?celular=2281237048

###
GET http://localhost:3000/api/estado-cuenta/estados
  ?rfc=GODR830305J19

###
POST http://localhost:3000/api/estado-cuenta/enviar-codigo
Content-Type: application/json

{
  "celular": "2281237048",
  "rfc": "TOMB971024UW4"
}

###
POST http://localhost:3000/api/estado-cuenta/validar-codigo
Content-Type: application/json

{
  "rfc": "TOMB971024UW4",
  "codigo": "869284"
}

###

POST http://localhost:3000/api/estado-cuenta/imprimir
Content-Type: application/json

{
  "rfc": "TOMB971024UW4",
  "codigo": "869284"
}

###
POST http://localhost:3000/api/estado-cuenta/generar-pdf
Content-Type: application/json

{
  "idOrden": 714442
}

###
POST https://api-ssl.bitly.com/v4/shorten
Content-Type: application/json
Authorization: {{$dotenv BITLY_TOKEN_HEADER}} 

{
  "long_url": "https://s3.us-east-1.amazonaws.com/gbplus.inter3.testing/paynet/564427_op.pdf"
}


### 
POST http://localhost:3000/api/estado-cuenta/send-sms
Content-Type: application/json

{
  "rfc": "TEST651002AJ1",
  "idOrden": "714442VD"
}